### ISSUE TITLE
 Machine provisioning fails creating vnc client when using PROXMOX_TOKENID

### ISSUE THREAD

**Issue by stenwt** [k8s-proxmox/cluster-api-provider-proxmox#182]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I used an API token to create a cluster. I set these env vars:

PROXMOX_PASSWORD=""
PROXMOX_SECRET=my-super-secret
PROXMOX_TOKENID=capmox@pve1!capmox1
PROXMOX_USER=capmox@pve1

then ran:

clusterctl generate cluster cappx-test --control-plane-machine-count=3 --infrastructure=proxmox:v0.3.5 --config https://raw.githubusercontent.com/k8s-proxmox/cluster-api-provider-proxmox/main/clusterctl.yaml > cappx-test.yaml 

after applying that config, no machines are created and I see this in the cappx-controller-manager log:

`I0819 02:24:18.852272       1 image.go:38] "setting cloud image" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-7gksx" namespace="default" name="cappx-test-7gksx" reconcileID=eba81345-28aa-46a6-b919-06123691991b E0819 02:24:19.850455       1 qemu.go:42] "failed to create qemu" err="failed to create vnc client: 500 - 500 value 'capmox@pve1!capmox1' does not look like a valid user name - {\"data\":null}" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-7gksx" namespace="default" name="cappx-test-7gksx" reconcileID=eba81345-28aa-46a6-b919-06123691991b E0819 02:24:19.850470       1 reconcile.go:27] "failed to create/get instance" err="failed to create vnc client: 500 - 500 value 'capmox@pve1!capmox1' does not look like a valid user name - {\"data\":null}" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-7gksx" namespace="default" name="cappx-test-7gksx" reconcileID=eba81345-28aa-46a6-b919-06123691991b E0819 02:24:19.850477       1 proxmoxmachine_controller.go:160] "Reconcile error" err="failed to create vnc client: 500 - 500 value 'capmox@pve1!capmox1' does not look like a valid user name - {\"data\":null}" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-7gksx" namespace="default" name="cappx-test-7gksx" reconcileID=eba81345-28aa-46a6-b919-06123691991b E0819 02:24:19.850803       1 controller.go:324] "Reconciler error" err="failed to create vnc client: 500 - 500 value 'capmox@pve1!capmox1' does not look like a valid user name - {\"data\":null}" controller="proxmoxmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="ProxmoxMachine" ProxmoxMachine="default/cappx-test-7gksx" namespace="default" name="cappx-test-7gksx" reconcileID=eba81345-28aa-46a6-b919-06123691991b `

**What did you expect to happen:**

Machine should be created 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-proxmox version: v0.3.5
- Proxmox VE version: 8.2.4
- Kubernetes version: (use `kubectl version`): 1.27.3
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

**Comment by robinelfrink** [comment]
I am experiencing exactly the same.

- Cluster-api-provider-proxmox version: 0.3.5
- Proxmox VE version: 8.2.4
- Kubernetes version: 1.30.2
- OS: Debian Bookworm (12.6)

**Comment by sp-yduck** [comment]
@stenwt @robinelfrink 
yes this is the know issue. this is came from proxmox side limitation. until proxmox support api token for vnc endpoint, please use user/pass instead. closing as duplicate #65
